FROM fedora

RUN dnf install --assumeyes protobuf
RUN dnf install --assumeyes zeromq
RUN dnf clean all

WORKDIR /app
COPY weather_raw_store .

EXPOSE 5557  # Service port
EXPOSE 6557  # Tap port

# Configure the container to write raw logs in /data/.
ENV WEATHER_RAW_STORE_LOG_PATH_PREFIX=/data/

CMD [ "./weather_raw_store" ]
